@version: 4.10
@include "scl.conf"

source s_network {
    udp(ip(0.0.0.0) port(514));
    tcp(ip(0.0.0.0) port(514));
};

rewrite r_strip_prefix {
    subst(
        "^.*?(\\{\"time\":)",
        "{\"time\":",
        value("MESSAGE"),
        type("pcre")
    );

};

destination d_vault {
    file(
        "/var/log/qxvault/vault.log"
        # Enable native log rotation natively
        logrotate(
            enable(yes)
            size(50MB)      # Rotate when the file hits 50 Megabytes
            rotations(5)    # Keep 5 historical archives
        )
    );
};

destination d_vault_audit {
   file(
      "/var/log/qxvault/vault-audit.log"
      template("${MESSAGE}\n")
      logrotate(
          enable(yes)
          size(50MB)      # Rotate when the file hits 50 Megabytes
          rotations(5)    # Keep 5 historical archives
      )
   );
};

filter f_vault_audit {

    message("\"time\":\"")
    and
    (
        message("\"type\":\"request\"")
        or
        message("\"type\":\"response\"")
    );

};

log {
    source(s_network);
    filter(f_vault_audit);
    rewrite(r_strip_prefix);
    destination(d_vault_audit);
    flags(final);
};

log {
    source(s_network);
    destination(d_vault);
};

