@version: 4.10
@include "scl.conf"

source s_network {
    udp(ip(0.0.0.0) port(514));
    tcp(ip(0.0.0.0) port(514));
};

destination d_vault {
    file(
        "/var/log/qxvault/vault-audit.log"
        # Enable native log rotation natively
        logrotate(
            enable(yes)
            size(50MB)      # Rotate when the file hits 50 Megabytes
            rotations(5)    # Keep 5 historical archives
        )
    );
};

#filter f_vault { message("vault"); };

log {
    source(s_network);
    #filter(f_vault);
    destination(d_vault);
};
