apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pagila-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pagila-db
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: pagila
  template:
    metadata:
      labels:
        app: pagila
    spec:

      initContainers:
      - name: download-pagila
        image: docker.io/curlimages/curl:latest
        command:
          - sh
          - -c
          - |
            set -eux

            curl -L \
              https://raw.githubusercontent.com/devrimgunduz/pagila/master/pagila-schema.sql \
              -o /initdb/01-pagila-schema.sql

            curl -L \
              https://raw.githubusercontent.com/devrimgunduz/pagila/master/pagila-data.sql \
              -o /initdb/02-pagila-data.sql

            ls -lh /initdb

        volumeMounts:
        - name: initdb
          mountPath: /initdb

      containers:
      - name: postgres
        image: docker.io/library/postgres:15

        ports:
        - containerPort: 5432

        env:
        - name: POSTGRES_USER
          value: postgres

        - name: POSTGRES_PASSWORD
          value: pagila

        - name: POSTGRES_DB
          value: pagila

        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata

        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data

        - name: initdb
          mountPath: /docker-entrypoint-initdb.d

      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: pagila-pvc

      - name: initdb
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: pagila-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app: pagila
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
    nodePort: 30432
